/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Alone;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author MZ
 */
public class MotifGroup_Finder_main {
    public static void main(String args[]) throws IOException {  
        // TODO add your handling code here:
        TaskTimer timer = new TaskTimer();
        timer.start();

        String[] patternArray = new String[16];
        patternArray[0] = "ACGA";
        patternArray[1] = "ACGC";
        patternArray[2] = "ACGG";
        patternArray[3] = "ACGT";
        patternArray[4] = "CCGA";
        patternArray[5] = "CCGC";
        patternArray[6] = "CCGG";
        patternArray[7] = "CCGT";
        patternArray[8] = "GCGA";
        patternArray[9] = "GCGC";
        patternArray[10] = "GCGG";
        patternArray[11] = "GCGT";
        patternArray[12] = "TCGA";
        patternArray[13] = "TCGC";
        patternArray[14] = "TCGG";
        patternArray[15] = "TCGT";
        Long[] patternNum = new Long[16];
        for(int i=0; i<patternNum.length; i++) patternNum[i] = 0L;
        
        for(int i=5; i>0; i--){ #number of chromosome
            String referenceFile = "Arabidopsis"+File.separator+"Arabidopsis_chr"+i+".fasta"; #input file 
            String chr = String.valueOf(i);
            Motif_Finder newOne = new Motif_Finder(referenceFile,chr);
            Long[] Strline= newOne.FinderMotif_group(patternArray);
            for(int j=0; j<Strline.length; j++) patternNum[j] = patternNum[j] + Strline[j];
            System.out.println("Chr "+i+" is done!");
        }
        String outputFile ="Arabidopsis"+File.separator+ "ArabidopsisDNA_PatternStaResults_Checkagain.txt";
        StringBuilder StrLine = new StringBuilder();  
        for(int i=0; i<patternNum.length; i++){
            String TempStr = patternArray[i] + "\t" + patternNum[i]+"\n";
            StrLine.append(TempStr);
        }
        Output.toFile(outputFile, "This file is generated by MotifGroup_Finder_main.java");
        Output.append(outputFile, StrLine.toString());
        StrLine.setLength(0);
        timer.stop();
        System.out.println("Well done!MotifGroup_Finder_main.java is working here!");
                
    }
}
